sdm660-common: Downgrade qti-telephony-common to LA.UM.8.2.r1-05100-sdm660.0
Updating blobs to LA.UM.8.2.r1-06700-sdm660.0 was leading to RIL breaks and show following error-

* E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getEssentialRecordsLoaded()Z in class Lcom/android/internal/telephony/uicc/IccRecords; or its super classes (declaration of 'com.android.internal.telephony.uicc.IccRecords' appears in /system/framework/telephony-common.jar)

Co-authored-by: Max Weffers <rcstar6696@gmail.com>
Signed-off-by: OdSazib <odsazib@gmail.com>